class Button():
    LEFT = 0
    CENTER = 1
    RIGHT = 2

class Key():
    """ Key codes for InputEmulation.Keyboard object.

    Can be entered directly or concatenated with an existing string, e.g. ``type(Key.TAB)`` """
    ENTER 		= "{ENTER}"
    ESC 		= "{ESC}"
    BACKSPACE 	= "{BACKSPACE}"
    DELETE 		= "{DELETE}"
    F1 			= "{F1}"
    F2 			= "{F2}"
    F3 			= "{F3}"
    F4 			= "{F4}"
    F5 			= "{F5}"
    F6 			= "{F6}"
    F7 			= "{F7}"
    F8 			= "{F8}"
    F9 			= "{F9}"
    F10 		= "{F10}"
    F11 		= "{F11}"
    F12 		= "{F12}"
    F13 		= "{F13}"
    F14 		= "{F14}"
    F15 		= "{F15}"
    F16 		= "{F16}"
    HOME 		= "{HOME}"
    END 		= "{END}"
    LEFT 		= "{LEFT}"
    RIGHT 		= "{RIGHT}"
    DOWN 		= "{DOWN}"
    UP 			= "{UP}"
    PAGE_DOWN 	= "{PAGE_DOWN}"
    PAGE_UP 	= "{PAGE_UP}"
    TAB			= "{TAB}"
    CAPS_LOCK 	= "{CAPS_LOCK}"
    NUM_LOCK	= "{NUM_LOCK}"
    SCROLL_LOCK	= "{SCROLL_LOCK}"
    INSERT		= "{INSERT}"
    SPACE		= "{SPACE}"
    PRINTSCREEN = "{PRINTSCREEN}"
    ALT 		= "{ALT}"
    CMD 		= "{CMD}"
    CTRL 	= "{CTRL}"
    META 		= "{META}"
    SHIFT 		= "{SHIFT}"
    WIN 		= "{WIN}"
    PAUSE		= "{PAUSE}"
    NUM0		= "{NUM0}"
    NUM1		= "{NUM1}"
    NUM2		= "{NUM2}"
    NUM3		= "{NUM3}"
    NUM4		= "{NUM4}"
    NUM5		= "{NUM5}"
    NUM6		= "{NUM6}"
    NUM7		= "{NUM7}"
    NUM8		= "{NUM8}"
    NUM9		= "{NUM9}"
    SEPARATOR	= "{SEPARATOR}"
    ADD		    = "{ADD}"
    MINUS		= "{MINUS}"
    MULTIPLY	= "{MULTIPLY}"
    DIVIDE		= "{DIVIDE}"

class KeyModifier():
    """ Can be used with type() to modify another key, e.g. ``type(Key.DELETE, Key.CTRL+Key.ALT)`` """
    CTRL 		= "{CTRL}"
    SHIFT 		= "{SHIFT}"
    ALT 		= "{ALT}"
    META 		= "{META}"
    CMD 		= "{CMD}"
    WIN 		= "{WIN}"